//임시 자료임.
export const WantedPlus_data = [
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210701/5/68653527.jpg",
        title: "성장하는 서버 개발자 되기",
        desc: "성장하는 서버 개발자 되기 : Live Talk #28",
        who: "당근마켓 변규현, WEVERSE 송주영",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20201013/14/67774782.jpg",
        title: "배달의민족 생존을 위한 마이크로서비스 ",
        desc: "개발자가 일 더 잘하는 법 : Wanted Con",
        who: "우아한형제들 김영한",
        time: "1:03:43",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210720/7/92862165.jpg",
        title: "누구에게나 처음은 있었다: Web ",
        desc: "Web Developer 누구에게나 처음은 있었다: ",
        who: "뱅크샐러드 이동근, 다노 김벼욱",
        time: "1:53:38",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210707/12/70418717.jpg",
        title: "바로 실행할 수 있는 다양한 QA이야기",
        desc: "QA 조직에서의 Test Automation 구축",
        who: "에이치피프린팅코리아 박정",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210707/12/94136542.jpg",
        title: "애자일 테스트에서 살아남기",
        desc: "바로 실행할 수 있는 다양한 QA이야기",
        who: "원티드랩 이승훈",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210701/5/68653527.jpg",
        title: "성장하는 서버 개발자 되기",
        desc: "성장하는 서버 개발자 되기 : Live Talk #28",
        who: "당근마켓 변규현, WEVERSE 송주영",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20201013/14/67774782.jpg",
        title: "배달의민족 생존을 위한 마이크로서비스 ",
        desc: "개발자가 일 더 잘하는 법 : Wanted Con",
        who: "우아한형제들 김영한",
        time: "1:03:43",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210720/7/92862165.jpg",
        title: "누구에게나 처음은 있었다: Web ",
        desc: "Web Developer 누구에게나 처음은 있었다: ",
        who: "뱅크샐러드 이동근, 다노 김벼욱",
        time: "1:53:38",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210707/12/70418717.jpg",
        title: "바로 실행할 수 있는 다양한 QA이야기",
        desc: "QA 조직에서의 Test Automation 구축",
        who: "에이치피프린팅코리아 박정",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210707/12/94136542.jpg",
        title: "애자일 테스트에서 살아남기",
        desc: "바로 실행할 수 있는 다양한 QA이야기",
        who: "원티드랩 이승훈",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210701/5/68653527.jpg",
        title: "성장하는 서버 개발자 되기",
        desc: "성장하는 서버 개발자 되기 : Live Talk #28",
        who: "당근마켓 변규현, WEVERSE 송주영",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20201013/14/67774782.jpg",
        title: "배달의민족 생존을 위한 마이크로서비스 ",
        desc: "개발자가 일 더 잘하는 법 : Wanted Con",
        who: "우아한형제들 김영한",
        time: "1:03:43",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210720/7/92862165.jpg",
        title: "누구에게나 처음은 있었다: Web ",
        desc: "Web Developer 누구에게나 처음은 있었다: ",
        who: "뱅크샐러드 이동근, 다노 김벼욱",
        time: "1:53:38",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210707/12/70418717.jpg",
        title: "바로 실행할 수 있는 다양한 QA이야기",
        desc: "QA 조직에서의 Test Automation 구축",
        who: "에이치피프린팅코리아 박정",
        time: "1:33:41",
    },
    {
        img: "https://wanted.video.kr.kollus.com/kr/snapshot/wanted/20210707/12/94136542.jpg",
        title: "애자일 테스트에서 살아남기",
        desc: "바로 실행할 수 있는 다양한 QA이야기",
        who: "원티드랩 이승훈",
        time: "1:33:41",
    },
];
