export const wdJob_data = [
    {
        cardId: "1",
        url: "https://static.wanted.co.kr/images/company/1017/3262_2_0.46d52ffb__400_400.jpg",
        title: "디지털 콘텐츠 플래닝&amp;카피라이터_게임콘텐츠 제작",
        company: "웹스프레드(webspread)",
        location: "서울",
        country: "한국",
        reward: "1,000,000원",
    },
    {
        cardId: "1",
        url: "https://static.wanted.co.kr/images/company/1017/3262_2_0.46d52ffb__400_400.jpg",
        title: "디지털 콘텐츠 플래닝&amp;카피라이터_게임콘텐츠 제작",
        company: "웹스프레드(webspread)",
        location: "서울",
        country: "한국",
        reward: "1,000,000원",
    },
    {
        cardId: "1",
        url: "https://static.wanted.co.kr/images/company/1017/3262_2_0.46d52ffb__400_400.jpg",
        title: "디지털 콘텐츠 플래닝&amp;카피라이터_게임콘텐츠 제작",
        company: "웹스프레드(webspread)",
        location: "서울",
        country: "한국",
        reward: "1,000,000원",
    },
    {
        cardId: "1",
        url: "https://static.wanted.co.kr/images/company/1017/3262_2_0.46d52ffb__400_400.jpg",
        title: "디지털 콘텐츠 플래닝&amp;카피라이터_게임콘텐츠 제작",
        company: "웹스프레드(webspread)",
        location: "서울",
        country: "한국",
        reward: "1,000,000원",
    },
    {
        cardId: "1",
        url: "https://static.wanted.co.kr/images/company/1017/3262_2_0.46d52ffb__400_400.jpg",
        title: "디지털 콘텐츠 플래닝&amp;카피라이터_게임콘텐츠 제작",
        company: "웹스프레드(webspread)",
        location: "서울",
        country: "한국",
        reward: "1,000,000원",
    },
    {
        cardId: "1",
        url: "https://static.wanted.co.kr/images/company/1017/3262_2_0.46d52ffb__400_400.jpg",
        title: "디지털 콘텐츠 플래닝&amp;카피라이터_게임콘텐츠 제작",
        company: "웹스프레드(webspread)",
        location: "서울",
        country: "한국",
        reward: "1,000,000원",
    },
];
